//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryorCalendarLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Cal_Event = new HashSet<Cal_Event>();
        }
    
        public System.Guid User_ID { get; set; }
        public string User_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_Num { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Cal_Event> Cal_Event { get; set; }
    }
}
